// AUTO-GENERATED by scripts/genLocations.cjs from the UEX Corp API (api.uexcorp.space).
// Live Stanton + Pyro stations, outposts & cities; moons folded into their parent planet.
// Do NOT edit by hand — re-run `node scripts/genLocations.cjs` to refresh after a patch.
// Trailing comment per row = source system/planet[/moon] (· cargo = has a freight elevator).
import type { SCLocation } from './locations'

export const LOCATIONS: SCLocation[] = [
  { id: "arc-l1", name: "ARC-L1 Wide Forest Station", planet: "arccorp", localMin: 3, keywords: ["arc-l1 wide forest station","arc-l1","arccorp l1","arccorp's l1"] }, // Stanton/ArcCorp
  { id: "arc-l2", name: "ARC-L2 Lively Pathway Station", planet: "arccorp", localMin: 3, keywords: ["arc-l2 lively pathway station","arc-l2","arccorp l2","arccorp's l2"] }, // Stanton/ArcCorp
  { id: "arc-l3", name: "ARC-L3 Modern Express Station", planet: "arccorp", localMin: 3, keywords: ["arc-l3 modern express station","arc-l3","arccorp l3","arccorp's l3"] }, // Stanton/ArcCorp
  { id: "arc-l4", name: "ARC-L4 Faint Glen Station", planet: "arccorp", localMin: 3, keywords: ["arc-l4 faint glen station","arc-l4","arccorp l4","arccorp's l4"] }, // Stanton/ArcCorp
  { id: "arc-l5", name: "ARC-L5 Yellow Core Station", planet: "arccorp", localMin: 3, keywords: ["arc-l5 yellow core station","arc-l5","arccorp l5","arccorp's l5"] }, // Stanton/ArcCorp
  { id: "arccorp-045", name: "ArcCorp Mining Area 045", planet: "arccorp", localMin: 6, keywords: ["arccorp mining area 045","arccorp 045","arccorp mining area045"] }, // Stanton/ArcCorp/Wala
  { id: "arccorp-048", name: "ArcCorp Mining Area 048", planet: "arccorp", localMin: 6, keywords: ["arccorp mining area 048","arccorp 048","arccorp mining area048"] }, // Stanton/ArcCorp/Wala
  { id: "arccorp-056", name: "ArcCorp Mining Area 056", planet: "arccorp", localMin: 6, keywords: ["arccorp mining area 056","arccorp 056","arccorp mining area056"] }, // Stanton/ArcCorp/Wala
  { id: "arccorp-061", name: "ArcCorp Mining Area 061", planet: "arccorp", localMin: 6, keywords: ["arccorp mining area 061","arccorp 061","arccorp mining area061"] }, // Stanton/ArcCorp/Wala
  { id: "area-18", name: "Area 18", planet: "arccorp", localMin: 6, keywords: ["area 18","area18"] }, // Stanton/ArcCorp
  { id: "baijini", name: "Baijini Point", planet: "arccorp", localMin: 1, keywords: ["baijini point","baijini"] }, // Stanton/ArcCorp · cargo
  { id: "humboldt", name: "Humboldt Mines", planet: "arccorp", localMin: 6, keywords: ["humboldt mines","humboldt"] }, // Stanton/ArcCorp/Lyria
  { id: "loveridge", name: "Loveridge Mineral Reserve", planet: "arccorp", localMin: 6, keywords: ["loveridge mineral reserve","loveridge"] }, // Stanton/ArcCorp/Lyria
  { id: "paradise", name: "Paradise Cove", planet: "arccorp", localMin: 6, keywords: ["paradise cove","paradise"] }, // Stanton/ArcCorp/Wala
  { id: "samson", name: "Samson & Son's Salvage Center", planet: "arccorp", localMin: 6, keywords: ["samson & son's salvage center","samson"] }, // Stanton/ArcCorp/Wala
  { id: "samson-x", name: "Shady Glen", planet: "arccorp", localMin: 6, keywords: ["shady glen","samson"] }, // Stanton/ArcCorp/Wala
  { id: "shubin-sal-2", name: "Shubin Mining Facility SAL-2", planet: "arccorp", localMin: 6, keywords: ["shubin mining facility sal-2","shubin sal-2"] }, // Stanton/ArcCorp/Lyria
  { id: "shubin-sal-5", name: "Shubin Mining Facility SAL-5", planet: "arccorp", localMin: 6, keywords: ["shubin mining facility sal-5","shubin sal-5"] }, // Stanton/ArcCorp/Lyria
  { id: "orphanage", name: "The Orphanage", planet: "arccorp", localMin: 6, keywords: ["the orphanage","orphanage"] }, // Stanton/ArcCorp/Lyria
  { id: "arccorp-141", name: "ArcCorp Mining Area 141", planet: "crusader", localMin: 6, keywords: ["arccorp mining area 141","arccorp 141","arccorp mining area141"] }, // Stanton/Crusader/Daymar
  { id: "arccorp-157", name: "ArcCorp Mining Area 157", planet: "crusader", localMin: 6, keywords: ["arccorp mining area 157","arccorp 157","arccorp mining area157"] }, // Stanton/Crusader/Yela
  { id: "benson", name: "Benson Mining Outpost", planet: "crusader", localMin: 6, keywords: ["benson mining outpost","benson"] }, // Stanton/Crusader/Yela
  { id: "bontiful", name: "Bountiful Harvest Hydroponics", planet: "crusader", localMin: 6, keywords: ["bountiful harvest hydroponics","bontiful"] }, // Stanton/Crusader/Daymar
  { id: "brio-s", name: "Brio's Breaker Yard", planet: "crusader", localMin: 6, keywords: ["brio's breaker yard","brio's"] }, // Stanton/Crusader/Daymar
  { id: "cru-l1", name: "CRU-L1 Ambitious Dream Station", planet: "crusader", localMin: 3, keywords: ["cru-l1 ambitious dream station","cru-l1","crusader l1","crusader's l1"] }, // Stanton/Crusader
  { id: "cru-l4", name: "CRU-L4 Shallow Fields Station", planet: "crusader", localMin: 3, keywords: ["cru-l4 shallow fields station","cru-l4","crusader l4","crusader's l4"] }, // Stanton/Crusader
  { id: "cru-l5", name: "CRU-L5 Beautiful Glen Station", planet: "crusader", localMin: 3, keywords: ["cru-l5 beautiful glen station","cru-l5","crusader l5","crusader's l5"] }, // Stanton/Crusader
  { id: "deakins", name: "Deakins Research", planet: "crusader", localMin: 6, keywords: ["deakins research","deakins"] }, // Stanton/Crusader/Yela
  { id: "gallete", name: "Gallete Family Farms", planet: "crusader", localMin: 6, keywords: ["gallete family farms","gallete"] }, // Stanton/Crusader/Cellin
  { id: "grim-hex", name: "Green Imperial Housing Exchange", planet: "crusader", localMin: 3, keywords: ["green imperial housing exchange","grim hex"] }, // Stanton/Crusader/Yela
  { id: "hickes", name: "Hickes Research", planet: "crusader", localMin: 6, keywords: ["hickes research","hickes"] }, // Stanton/Crusader/Cellin
  { id: "jumpdown", name: "Jumptown", planet: "crusader", localMin: 6, keywords: ["jumptown","jumpdown"] }, // Stanton/Crusader/Yela
  { id: "jumptown", name: "Jumptown", planet: "crusader", localMin: 6, keywords: ["jumptown"] }, // Stanton/Crusader/Daymar
  { id: "kudre-ore", name: "Kudre Ore", planet: "crusader", localMin: 6, keywords: ["kudre ore"] }, // Stanton/Crusader/Daymar
  { id: "nt-999-xx", name: "NT-999-XX", planet: "crusader", localMin: 6, keywords: ["nt-999-xx"] }, // Stanton/Crusader/Yela
  { id: "nt999ii", name: "NT-999-XXII", planet: "crusader", localMin: 6, keywords: ["nt-999-xxii","nt999ii"] }, // Stanton/Crusader/Yela
  { id: "nuen", name: "Nuen Waste Management", planet: "crusader", localMin: 6, keywords: ["nuen waste management","nuen"] }, // Stanton/Crusader/Daymar
  { id: "orison", name: "Orison", planet: "crusader", localMin: 6, keywords: ["orison"] }, // Stanton/Crusader
  { id: "private", name: "Private Property", planet: "crusader", localMin: 6, keywords: ["private property","private"] }, // Stanton/Crusader/Cellin
  { id: "seraphim", name: "Seraphim Station", planet: "crusader", localMin: 1, keywords: ["seraphim station","seraphim"] }, // Stanton/Crusader · cargo
  { id: "shubin-scd1", name: "Shubin Mining Facility SCD-1", planet: "crusader", localMin: 6, keywords: ["shubin mining facility scd-1","shubin scd1"] }, // Stanton/Crusader/Daymar
  { id: "terra-mills", name: "Terra Mills HydroFarm", planet: "crusader", localMin: 6, keywords: ["terra mills hydrofarm","terra mills"] }, // Stanton/Crusader/Cellin
  { id: "tram", name: "Tram & Myers Mining", planet: "crusader", localMin: 6, keywords: ["tram & myers mining","tram"] }, // Stanton/Crusader/Cellin
  { id: "cutter-s-rig", name: "Cutter's Rig", planet: "hurston", localMin: 6, keywords: ["cutter's rig"] }, // Stanton/Hurston
  { id: "everus", name: "Everus Harbor", planet: "hurston", localMin: 1, keywords: ["everus harbor","everus"] }, // Stanton/Hurston · cargo
  { id: "finn-s-folly", name: "Finn's Folly", planet: "hurston", localMin: 6, keywords: ["finn's folly"] }, // Stanton/Hurston
  { id: "anderson", name: "HDMS-Anderson", planet: "hurston", localMin: 6, keywords: ["hdms-anderson","anderson"] }, // Stanton/Hurston/Aberdeen
  { id: "bezdek", name: "HDMS-Bezdek", planet: "hurston", localMin: 6, keywords: ["hdms-bezdek","bezdek"] }, // Stanton/Hurston/Arial
  { id: "edmond", name: "HDMS-Edmond", planet: "hurston", localMin: 6, keywords: ["hdms-edmond","edmond"] }, // Stanton/Hurston
  { id: "hadley", name: "HDMS-Hadley", planet: "hurston", localMin: 6, keywords: ["hdms-hadley","hadley"] }, // Stanton/Hurston
  { id: "hahn", name: "HDMS-Hahn", planet: "hurston", localMin: 6, keywords: ["hdms-hahn","hahn"] }, // Stanton/Hurston/Magda
  { id: "lathan", name: "HDMS-Lathan", planet: "hurston", localMin: 6, keywords: ["hdms-lathan","lathan"] }, // Stanton/Hurston/Arial
  { id: "norgaard", name: "HDMS-Norgaard", planet: "hurston", localMin: 6, keywords: ["hdms-norgaard","norgaard"] }, // Stanton/Hurston/Aberdeen · cargo
  { id: "oparei", name: "HDMS-Oparei", planet: "hurston", localMin: 6, keywords: ["hdms-oparei","oparei"] }, // Stanton/Hurston
  { id: "perlman", name: "HDMS-Perlman", planet: "hurston", localMin: 6, keywords: ["hdms-perlman","perlman"] }, // Stanton/Hurston/Magda
  { id: "pinewood", name: "HDMS-Pinewood", planet: "hurston", localMin: 6, keywords: ["hdms-pinewood","pinewood"] }, // Stanton/Hurston · cargo
  { id: "ryder", name: "HDMS-Ryder", planet: "hurston", localMin: 6, keywords: ["hdms-ryder","ryder"] }, // Stanton/Hurston/Ita
  { id: "stanhope", name: "HDMS-Stanhope", planet: "hurston", localMin: 6, keywords: ["hdms-stanhope","stanhope"] }, // Stanton/Hurston
  { id: "thedus", name: "HDMS-Thedus", planet: "hurston", localMin: 6, keywords: ["hdms-thedus","thedus"] }, // Stanton/Hurston
  { id: "woodruff", name: "HDMS-Woodruff", planet: "hurston", localMin: 6, keywords: ["hdms-woodruff","woodruff"] }, // Stanton/Hurston/Ita
  { id: "hur-l1", name: "HUR-L1 Green Glade Station", planet: "hurston", localMin: 3, keywords: ["hur-l1 green glade station","hur-l1","hurston l1","hurston's l1"] }, // Stanton/Hurston · cargo
  { id: "hur-l2", name: "HUR-L2 Faithful Dream Station", planet: "hurston", localMin: 3, keywords: ["hur-l2 faithful dream station","hur-l2","hurston l2","hurston's l2"] }, // Stanton/Hurston
  { id: "hur-l3", name: "HUR-L3 Thundering Express Station", planet: "hurston", localMin: 3, keywords: ["hur-l3 thundering express station","hur-l3","hurston l3","hurston's l3"] }, // Stanton/Hurston
  { id: "hur-l4", name: "HUR-L4 Melodic Fields Station", planet: "hurston", localMin: 3, keywords: ["hur-l4 melodic fields station","hur-l4","hurston l4","hurston's l4"] }, // Stanton/Hurston
  { id: "hur-l5", name: "HUR-L5 High Course Station", planet: "hurston", localMin: 3, keywords: ["hur-l5 high course station","hur-l5","hurston l5","hurston's l5"] }, // Stanton/Hurston
  { id: "lorville", name: "Lorville", planet: "hurston", localMin: 6, keywords: ["lorville"] }, // Stanton/Hurston
  { id: "ludlow", name: "Ludlow", planet: "hurston", localMin: 6, keywords: ["ludlow"] }, // Stanton/Hurston
  { id: "makers", name: "Maker's Point", planet: "hurston", localMin: 6, keywords: ["maker's point","makers"] }, // Stanton/Hurston
  { id: "pickers", name: "Picker's Field", planet: "hurston", localMin: 6, keywords: ["picker's field","pickers"] }, // Stanton/Hurston
  { id: "rappel", name: "Rappel", planet: "hurston", localMin: 6, keywords: ["rappel"] }, // Stanton/Hurston
  { id: "reclamation", name: "Reclamation & Disposal Orinth", planet: "hurston", localMin: 6, keywords: ["reclamation & disposal orinth","reclamation"] }, // Stanton/Hurston
  { id: "sakura-sun-magnolia", name: "Sakura Sun Magnolia Workcenter", planet: "hurston", localMin: 6, keywords: ["sakura sun magnolia workcenter","sakura sun magnolia"] }, // Stanton/Hurston · cargo
  { id: "weeping-cove", name: "Weeping Cove", planet: "hurston", localMin: 6, keywords: ["weeping cove"] }, // Stanton/Hurston
  { id: "zephyr", name: "Zephyr", planet: "hurston", localMin: 6, keywords: ["zephyr"] }, // Stanton/Hurston
  { id: "astor-s", name: "Astor's Clearing", planet: "microtech", localMin: 6, keywords: ["astor's clearing","astor's"] }, // Stanton/MicroTech
  { id: "bloodshot-ridge", name: "Bloodshot Ridge", planet: "microtech", localMin: 6, keywords: ["bloodshot ridge"] }, // Stanton/MicroTech
  { id: "bud-s", name: "Bud's Growery", planet: "microtech", localMin: 6, keywords: ["bud's growery","bud's"] }, // Stanton/MicroTech/Euterpe
  { id: "devlin", name: "Devlin Scrap & Salvage", planet: "microtech", localMin: 6, keywords: ["devlin scrap & salvage","devlin"] }, // Stanton/MicroTech/Euterpe
  { id: "dunboro", name: "Dunboro", planet: "microtech", localMin: 6, keywords: ["dunboro"] }, // Stanton/MicroTech
  { id: "frostbite", name: "Frostbite", planet: "microtech", localMin: 6, keywords: ["frostbite"] }, // Stanton/MicroTech
  { id: "ghost-hollow", name: "Ghost Hollow", planet: "microtech", localMin: 6, keywords: ["ghost hollow"] }, // Stanton/MicroTech
  { id: "harper-s", name: "Harper's Point", planet: "microtech", localMin: 6, keywords: ["harper's point","harper's"] }, // Stanton/MicroTech
  { id: "ins-jericho", name: "INS Jericho", planet: "microtech", localMin: 3, keywords: ["ins jericho"] }, // Stanton/MicroTech
  { id: "mic-l1", name: "MIC-L1 Shallow Frontier Station", planet: "microtech", localMin: 3, keywords: ["mic-l1 shallow frontier station","mic-l1","microtech l1","microtech's l1"] }, // Stanton/MicroTech
  { id: "mic-l2", name: "MIC-L2 Long Forest Station", planet: "microtech", localMin: 3, keywords: ["mic-l2 long forest station","mic-l2","microtech l2","microtech's l2"] }, // Stanton/MicroTech
  { id: "mic-l3", name: "MIC-L3 Endless Odyssey Station", planet: "microtech", localMin: 3, keywords: ["mic-l3 endless odyssey station","mic-l3","microtech l3","microtech's l3"] }, // Stanton/MicroTech
  { id: "mic-l4", name: "MIC-L4 Red Crossroads Station", planet: "microtech", localMin: 3, keywords: ["mic-l4 red crossroads station","mic-l4","microtech l4","microtech's l4"] }, // Stanton/MicroTech
  { id: "mic-l5", name: "MIC-L5 Modern Icarus Station", planet: "microtech", localMin: 3, keywords: ["mic-l5 modern icarus station","mic-l5","microtech l5","microtech's l5"] }, // Stanton/MicroTech
  { id: "moreland-hills", name: "Moreland Hills", planet: "microtech", localMin: 6, keywords: ["moreland hills"] }, // Stanton/MicroTech
  { id: "new-babbage", name: "New Babbage", planet: "microtech", localMin: 6, keywords: ["new babbage"] }, // Stanton/MicroTech
  { id: "outpost-54", name: "Outpost 54", planet: "microtech", localMin: 6, keywords: ["outpost 54","outpost54"] }, // Stanton/MicroTech
  { id: "tressler", name: "Port Tressler", planet: "microtech", localMin: 1, keywords: ["port tressler","tressler"] }, // Stanton/MicroTech · cargo
  { id: "raven", name: "Raven's Roost", planet: "microtech", localMin: 6, keywords: ["raven's roost","raven"] }, // Stanton/MicroTech
  { id: "anvik", name: "Rayari Anvik Research Outpost", planet: "microtech", localMin: 6, keywords: ["rayari anvik research outpost","anvik"] }, // Stanton/MicroTech/Calliope
  { id: "cantwell", name: "Rayari Cantwell Research Outpost", planet: "microtech", localMin: 6, keywords: ["rayari cantwell research outpost","cantwell"] }, // Stanton/MicroTech/Clio
  { id: "deltana", name: "Rayari Deltana Research Outpost", planet: "microtech", localMin: 6, keywords: ["rayari deltana research outpost","deltana"] }, // Stanton/MicroTech
  { id: "kaltag", name: "Rayari Kaltag Research Outpost", planet: "microtech", localMin: 6, keywords: ["rayari kaltag research outpost","kaltag"] }, // Stanton/MicroTech/Calliope
  { id: "mcgrath", name: "Rayari McGrath Research Outpost", planet: "microtech", localMin: 6, keywords: ["rayari mcgrath research outpost","mcgrath"] }, // Stanton/MicroTech/Clio
  { id: "razor-s-edge", name: "Razor's Edge", planet: "microtech", localMin: 6, keywords: ["razor's edge"] }, // Stanton/MicroTech
  { id: "shubin-10", name: "Shubin Mining Facility SM0-10", planet: "microtech", localMin: 6, keywords: ["shubin mining facility sm0-10","shubin 10"] }, // Stanton/MicroTech
  { id: "shubin-13", name: "Shubin Mining Facility SM0-13", planet: "microtech", localMin: 6, keywords: ["shubin mining facility sm0-13","shubin 13"] }, // Stanton/MicroTech
  { id: "shubin-18", name: "Shubin Mining Facility SM0-18", planet: "microtech", localMin: 6, keywords: ["shubin mining facility sm0-18","shubin 18"] }, // Stanton/MicroTech
  { id: "shubin-22", name: "Shubin Mining Facility SM0-22", planet: "microtech", localMin: 6, keywords: ["shubin mining facility sm0-22","shubin 22"] }, // Stanton/MicroTech
  { id: "shubin-a6", name: "Shubin Mining Facility SMCa-6", planet: "microtech", localMin: 6, keywords: ["shubin mining facility smca-6","shubin a6"] }, // Stanton/MicroTech/Calliope
  { id: "shubin-a8", name: "Shubin Mining Facility SMCa-8", planet: "microtech", localMin: 6, keywords: ["shubin mining facility smca-8","shubin a8"] }, // Stanton/MicroTech/Calliope
  { id: "necropolis", name: "The Necropolis", planet: "microtech", localMin: 6, keywords: ["the necropolis","necropolis"] }, // Stanton/MicroTech
  { id: "gray-gardens-depot", name: "Gray Gardens Depot", planet: "pyro-i", localMin: 6, keywords: ["gray gardens depot"] }, // Pyro/Pyro I · cargo
  { id: "pyam-farstat-1-2", name: "PYAM-FARSTAT-1-2", planet: "pyro-i", localMin: 1, keywords: ["pyam-farstat-1-2"] }, // Pyro/Pyro I
  { id: "pyam-farstat-1-3", name: "PYAM-FARSTAT-1-3", planet: "pyro-i", localMin: 1, keywords: ["pyam-farstat-1-3"] }, // Pyro/Pyro I
  { id: "pyam-farstat-1-5", name: "PYAM-FARSTAT-1-5", planet: "pyro-i", localMin: 1, keywords: ["pyam-farstat-1-5"] }, // Pyro/Pyro I
  { id: "rustville", name: "Rustville", planet: "pyro-i", localMin: 6, keywords: ["rustville"] }, // Pyro/Pyro I · cargo
  { id: "stag-s-rut", name: "Stag's Rut", planet: "pyro-i", localMin: 6, keywords: ["stag's rut"] }, // Pyro/Pyro I
  { id: "arid-reach", name: "Arid Reach", planet: "pyro-ii", localMin: 6, keywords: ["arid reach"] }, // Pyro/Monox · cargo
  { id: "checkmate", name: "Checkmate Station", planet: "pyro-ii", localMin: 3, keywords: ["checkmate station","checkmate"] }, // Pyro/Monox · cargo
  { id: "jackson-s-swap", name: "Jackson's Swap", planet: "pyro-ii", localMin: 6, keywords: ["jackson's swap"] }, // Pyro/Monox · cargo
  { id: "last-ditch", name: "Last Ditch", planet: "pyro-ii", localMin: 6, keywords: ["last ditch"] }, // Pyro/Monox
  { id: "ostler-s-claim", name: "Ostler's Claim", planet: "pyro-ii", localMin: 6, keywords: ["ostler's claim"] }, // Pyro/Monox
  { id: "pyam-farstat-2-3", name: "PYAM-FARSTAT-2-3", planet: "pyro-ii", localMin: 3, keywords: ["pyam-farstat-2-3"] }, // Pyro/Monox
  { id: "slowburn-depot", name: "Slowburn Depot", planet: "pyro-ii", localMin: 6, keywords: ["slowburn depot"] }, // Pyro/Monox · cargo
  { id: "sunset-mesa", name: "Sunset Mesa", planet: "pyro-ii", localMin: 6, keywords: ["sunset mesa"] }, // Pyro/Monox · cargo
  { id: "yang-s-place", name: "Yang's Place", planet: "pyro-ii", localMin: 6, keywords: ["yang's place"] }, // Pyro/Monox
  { id: "bueno-ravine", name: "Bueno Ravine", planet: "pyro-iii", localMin: 6, keywords: ["bueno ravine"] }, // Pyro/Bloom · cargo
  { id: "carver-s-ridge", name: "Carver's Ridge", planet: "pyro-iii", localMin: 6, keywords: ["carver's ridge"] }, // Pyro/Bloom
  { id: "frigid-knot", name: "Frigid Knot", planet: "pyro-iii", localMin: 6, keywords: ["frigid knot"] }, // Pyro/Bloom · cargo
  { id: "narena-s-rest", name: "Narena's Rest", planet: "pyro-iii", localMin: 6, keywords: ["narena's rest"] }, // Pyro/Bloom
  { id: "orbituary", name: "Orbituary", planet: "pyro-iii", localMin: 1, keywords: ["orbituary"] }, // Pyro/Bloom · cargo
  { id: "patch-city", name: "Patch City", planet: "pyro-iii", localMin: 1, keywords: ["patch city"] }, // Pyro/Bloom · cargo
  { id: "prospect-depot", name: "Prospect Depot", planet: "pyro-iii", localMin: 6, keywords: ["prospect depot"] }, // Pyro/Bloom · cargo
  { id: "pyam-farstat-3-5", name: "PYAM-FARSTAT-3-5", planet: "pyro-iii", localMin: 1, keywords: ["pyam-farstat-3-5"] }, // Pyro/Bloom
  { id: "pyam-supvisr-3-4", name: "PYAM-SUPVISR-3-4", planet: "pyro-iii", localMin: 1, keywords: ["pyam-supvisr-3-4"] }, // Pyro/Bloom
  { id: "pyam-supvisr-3-5", name: "PYAM-SUPVISR-3-5", planet: "pyro-iii", localMin: 1, keywords: ["pyam-supvisr-3-5"] }, // Pyro/Bloom
  { id: "shadowfall", name: "Shadowfall", planet: "pyro-iii", localMin: 6, keywords: ["shadowfall"] }, // Pyro/Bloom
  { id: "shepherd-s-rest", name: "Shepherd's Rest", planet: "pyro-iii", localMin: 6, keywords: ["shepherd's rest"] }, // Pyro/Bloom · cargo
  { id: "starlight-service", name: "Starlight Service Station", planet: "pyro-iii", localMin: 3, keywords: ["starlight service station","starlight service"] }, // Pyro/Bloom · cargo
  { id: "the-golden-riviera", name: "The Golden Riviera", planet: "pyro-iii", localMin: 6, keywords: ["the golden riviera"] }, // Pyro/Bloom · cargo
  { id: "the-yard", name: "The Yard", planet: "pyro-iii", localMin: 6, keywords: ["the yard"] }, // Pyro/Bloom
  { id: "windfall", name: "Windfall", planet: "pyro-iii", localMin: 6, keywords: ["windfall"] }, // Pyro/Bloom
  { id: "chawla-s-beach", name: "Chawla's Beach", planet: "pyro-iv", localMin: 6, keywords: ["chawla's beach"] }, // Pyro/Pyro IV · cargo
  { id: "endgame", name: "Endgame", planet: "pyro-iv", localMin: 3, keywords: ["endgame"] }, // Pyro/Pyro IV · cargo
  { id: "fallow-field", name: "Fallow Field", planet: "pyro-iv", localMin: 6, keywords: ["fallow field"] }, // Pyro/Pyro IV · cargo
  { id: "goner-s-deal", name: "Goner's Deal", planet: "pyro-iv", localMin: 6, keywords: ["goner's deal"] }, // Pyro/Pyro IV · cargo
  { id: "pyam-farstat-6-2", name: "PYAM-FARSTAT-6-2", planet: "pyro-iv", localMin: 1, keywords: ["pyam-farstat-6-2"] }, // Pyro/Pyro IV
  { id: "sacren-s-plot", name: "Sacren's Plot", planet: "pyro-iv", localMin: 6, keywords: ["sacren's plot"] }, // Pyro/Pyro IV · cargo
  { id: "ashland", name: "Ashland", planet: "pyro-v", localMin: 6, keywords: ["ashland"] }, // Pyro/Pyro V/Ignis · cargo
  { id: "feo-canyon-depot", name: "Feo Canyon Depot", planet: "pyro-v", localMin: 6, keywords: ["feo canyon depot"] }, // Pyro/Pyro V/Fairo · cargo
  { id: "gaslight", name: "Gaslight", planet: "pyro-v", localMin: 3, keywords: ["gaslight"] }, // Pyro/Pyro V · cargo
  { id: "kabir-s-post", name: "Kabir's Post", planet: "pyro-v", localMin: 6, keywords: ["kabir's post"] }, // Pyro/Pyro V/Ignis · cargo
  { id: "porphet-s-peak", name: "Prophet's Peak", planet: "pyro-v", localMin: 6, keywords: ["prophet's peak","porphet's peak"] }, // Pyro/Pyro V/Adir
  { id: "pyam-farstat-5-1", name: "PYAM-FARSTAT-5-1", planet: "pyro-v", localMin: 1, keywords: ["pyam-farstat-5-1"] }, // Pyro/Pyro V
  { id: "pyam-farstat-5-3", name: "PYAM-FARSTAT-5-3", planet: "pyro-v", localMin: 3, keywords: ["pyam-farstat-5-3"] }, // Pyro/Pyro V
  { id: "rat-s-nest", name: "Rat's Nest", planet: "pyro-v", localMin: 3, keywords: ["rat's nest"] }, // Pyro/Pyro V · cargo
  { id: "rod-s-fuel-n-supplies", name: "Rod's Fuel 'N Supplies", planet: "pyro-v", localMin: 3, keywords: ["rod's fuel 'n supplies"] }, // Pyro/Pyro V · cargo
  { id: "seer-s-canyon", name: "Seer's Canyon", planet: "pyro-v", localMin: 6, keywords: ["seer's canyon"] }, // Pyro/Pyro V/Vatra · cargo
  { id: "blackrock-exchange", name: "Blackrock Exchange", planet: "pyro-vi", localMin: 6, keywords: ["blackrock exchange"] }, // Pyro/Terminus · cargo
  { id: "bullock-s-reach", name: "Bullock's Reach", planet: "pyro-vi", localMin: 6, keywords: ["bullock's reach"] }, // Pyro/Terminus
  { id: "canard-view", name: "Canard View", planet: "pyro-vi", localMin: 6, keywords: ["canard view"] }, // Pyro/Terminus · cargo
  { id: "dudley-daughters", name: "Dudley & Daughters", planet: "pyro-vi", localMin: 3, keywords: ["dudley & daughters"] }, // Pyro/Terminus · cargo
  { id: "kinder-plots", name: "Kinder Plots", planet: "pyro-vi", localMin: 6, keywords: ["kinder plots"] }, // Pyro/Terminus
  { id: "last-landings", name: "Last Landings", planet: "pyro-vi", localMin: 6, keywords: ["last landings"] }, // Pyro/Terminus · cargo
  { id: "megumi-refueling", name: "Megumi Refueling", planet: "pyro-vi", localMin: 3, keywords: ["megumi refueling"] }, // Pyro/Terminus · cargo
  { id: "rough-landing", name: "Rough Landing", planet: "pyro-vi", localMin: 6, keywords: ["rough landing"] }, // Pyro/Terminus · cargo
  { id: "ruin-station", name: "Ruin Station", planet: "pyro-vi", localMin: 1, keywords: ["ruin station"] }, // Pyro/Terminus · cargo
  { id: "scarper-s-turn", name: "Scarper's Turn", planet: "pyro-vi", localMin: 6, keywords: ["scarper's turn"] }, // Pyro/Terminus
  { id: "stonetree", name: "Stonetree", planet: "pyro-vi", localMin: 6, keywords: ["stonetree"] }, // Pyro/Terminus
]
